### ISSUE TITLE
Отсутствуют параметры, которые не описаны в документации Метрики

### ISSUE THREAD

**Issue by antonsnowy** [nixsolutions/yandex-php-library#103]
Столкнулся с такой проблемой: получал данные за несколько дней с группировкой "hours" (интервалы по несколько часов). В ответе есть дата начала/окончания периода выборки, но нет значений по сколько часов разбивается день, чтобы я мог правильно отрисовать данные и сопоставить значения со временем. Поддержка Яндекс.Метрики ответила, что нужно использовать параметры, которые не описаны в документации: auto_group_size. То есть день разбивается на auto_group_size часов.

Нужно добавить эти параметры в модели (ByTimeData и остальные): auto_group_size, auto_group_type, group.

Вот пример ответа:
{"query":{"ids":[xxx],"dimensions":[],"metrics":["ym:s:pageviews"],"sort":["-ym:s:pageviews"],"date1":"2015-09-21","date2":"2015-09-28","auto_group_size":8,"group":"hours","auto_group_type":"hours"},"data":[{"dimensions":[],"metrics":[[0.0,28.0,0.0,0.0,4.0,0.0,0.0,6.0,0.0,0.0,1.0,6.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,13.0,0.0]]}],"total_rows":6,"sampled":false,"sample_share":1.0,"sample_size":6,"sample_space":6,"data_lag":114,"totals":[[58.0]]}

**Comment by loginwashere** [comment]
Действительно в [документации](https://tech.yandex.ru/metrika/doc/api2/api_v1/bytime-docpage/) не нашел параметров  auto_group_size, auto_group_type и group в ответе, хотя параметр group есть в запросе.

Как я понимаю эти параметры теоретически можно добавить в Yandex\Metrica\Stat\Models\Query так как его использует Yandex\Metrica\Stat\Models\ByTimeData для мапинга параметров вложенных в query.

Нужно будет исследовать этот вопрос.
