### ISSUE TITLE
Error on upload 

### ISSUE THREAD

**Issue by gelid** [nixsolutions/yandex-php-library#112]
Hi. I am trying to upload  files on Yandex Disk with REST API (from the feedback of the site ) . I set up a script to localhost in chrome. However, other browsers ( Opera, and the fox ) get an error firefox_error.png, in chrome sometimes , too, is a error chrome.png

Scripts attached. all by documentation . I did not invent anything .
send.php - sending the script via the API
index.php - the button for the file

I try to use different versions of the library .
the result is the same

Добрый день. пытаюсь сделать загрузку файлов на яндекс диск (из обратки на сайте). настроил скрипт на локалхосте в хроме. Однако в других браузерах (опера и лиса) получаю ошибку firefox_error.png, в хроме иногда тоже бывает ошибка  chrome.png

Скприпты прилагаю. все по документации. ничего не изобретал.
send.php - скрипт отправки через API
index.php - кнопка для файла

пробовал использовать разные версии библиотеки.
результат такой же

send.php
```php
require_once 'phar://yandex-php-library_master.phar/vendor/autoload.php';
use Yandex\Disk\DiskClient;
$diskClient = new DiskClient('************************');
$diskClient->setServiceScheme(DiskClient::HTTPS_SCHEME);
$data = array();
$files = array();

foreach( $_FILES as $file ){
    $fileName = $file['tmp_name'];
    $newName = $file['name'];
    $diskClient->uploadFile(
        '/upload/',
        array(
            'path' => $fileName,
            'size' => filesize($fileName),
            'name' => $newName
        )
    );
    $files[] = $fileName;
}

$data = array('files' => $files );

echo json_encode( $data );
```

index.php
```html
<input name="file_p" type="file" value="" />
<span class="ajax-respond"><span></span></span>
<script type="text/javascript" src="https://ajax.googleapis.com/ajax/libs/jquery/1/jquery.min.js"></script>
<style>
span.ajax-respond {
    background-color: red;
    width: 100px;
    height: 15px;
    display: block;
}

span.ajax-respond span {
    background-color: blue;
    width: 0;
    height: 15px;
    display: block;
}
</style>
<script>
$(function(){
    $('input[type="file"]').change(function(){
        var files = this.files;
        var data = new FormData();
        $.each( files, function( key, value ){
            data.append( key, value );
        });
        
        $.ajax({
            xhr: function() {
                var xhr = new window.XMLHttpRequest();
              
                xhr.upload.addEventListener("progress", function(evt) {
                    if (evt.lengthComputable) {
                        var percentComplete = evt.loaded / evt.total;
                        percentComplete = parseInt(percentComplete * 100);
                        //прогресс
                        console.log(percentComplete);
                        $('.ajax-respond span').css('width',percentComplete);
                        if (percentComplete === 100) {
                        //100%
                        }
                    }
                }, false);
                return xhr;
            },
            url: 'send.php',
            type: "POST",
            data: data,
            processData: false,
            contentType: false,
            success: function(result) {
              console.log(result);
            }
        });


    })
})

    
</script>   
```

![chrome](https://cloud.githubusercontent.com/assets/14069982/10274549/9a19bdea-6b47-11e5-8779-55b249b7afe6.png)
![firefox_error](https://cloud.githubusercontent.com/assets/14069982/10274548/9a18ed34-6b47-11e5-8a11-a350b622d023.png)

**Comment by loginwashere** [comment]
Добрый день. 
Спасибо за подробное описание, но не совсем ясно какая версия библиотеки используется.

Можете проверить повторяется ли описанное поведение на свежем мастере (там был переход к использованию Guzzle 5.3 для работы с апи Yandex, а судя по приведенным ошибкам в вашей версии библиотеки еще используется 3я версия) и на библиотеке вирсии 0.4.1.

Я воспользовавшись вашими примерами скриптов попробовал воспроизвести проблему на этих версиях, но пока что не получилось.

Так же будет полезно узнать больше информации об окружении на котором воспроизводится ошибка - операционная система, версия php, загруженные расширения, веб сервер

**Comment by gelid** [comment]
Спасибо за быстрый ответ, действительно версия использовалась 0,4,1
Скачал последнюю версию master c https://yadi.sk/d/26YmC3hRByBd7
Разместил сразу на рабочем сервере (Debian, php5-5.4.39-0, apache2-2.2.22-13) - дабы исключить локальные проблемы с библиотеками
http://vsrok.ru/yandex/
Хром отрабатывает на ура.
В лисе и опере ошибки
```
<br />
<b>Fatal error</b>:  Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 55: SSL_write() returned SYSCALL, errno = 32' in phar:///var/www/bitrix/data/www/vsrok.ru/yandex/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
Stack trace:
#0 phar:///var/www/bitrix/data/www/vsrok.ru/yandex/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Object(GuzzleHttp\Ring\Client\CurlMultiHandler), Array, Array)
#1 phar:///var/www/bitrix/data/www/vsrok.ru/yandex/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlMultiHandler.php(242): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Object(GuzzleHttp\Ring\Client\CurlMultiHandler), Array, Array, Array, Resource id #157)
#2 phar:///var/www/bitrix/data/www/vsrok.ru/yandex/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlMultiHandler.php(136): GuzzleHttp\Ring\Client\CurlMultiHandler-&gt;processMe in <b>phar:///var/www/bitrix/data/www/vsrok.ru/yandex/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php</b> on line <b>51</b><br />
```
локалка:
Windows 7, OpenServer 5.1.1 (Apache 2.2, PHP 5.3) 
ошибка
![new_master](https://cloud.githubusercontent.com/assets/14069982/10276067/83ec87b0-6b55-11e5-94cd-753a4b82b09a.png)

**Comment by loginwashere** [comment]
@gelid в местере как я уже говорил используется Guzzle 5.3 а он требует php >= 5.4. Из-за этого ошибка на вашем локальном окружении.

По поводу ошибки в  Firefox и Opera - можете уточнить какие версии этих браузеров вы используете? Я попробовал глянуть в Firefox 40 и Opera 32 - загрузка отработала без ошибок.

**Comment by gelid** [comment]
Опера 32.0.1948.69
Лиса 40.0.3

пробовал с нескольких компов

**Comment by loginwashere** [comment]
Хм, учитывая что в хроме все работает, возможно проблема в не в библиотеке.
Можете проверить что в send.php при отправке из всех трех браузеров передаеются верные параметры при вызове ```$diskClient->uploadFile```

**Comment by gelid** [comment]
Хром fileName:/tmp/phpM6zAmr----filesize:845941----newName:Desert.jpg----
Опера  fileName:/tmp/php4DY4TY----filesize:845941----newName:Desert.jpg----
Лиса fileName:/tmp/phpBoRZxv----filesize:845941----newName:Desert.jpg----

все вроде нормально

**Comment by gelid** [comment]
вот с 10 попытки хром туда же . ошибка 
![new_master](https://cloud.githubusercontent.com/assets/14069982/10277632/e57b6cd0-6b5f-11e5-9978-ea46fd0fc909.png)

**Comment by loginwashere** [comment]
Удалось воспроизвести локально с файлом размером примерно с ваш.
Пока еще не понял в чем дело. Буду смотреть.

**Comment by loginwashere** [comment]
Причем у меня файл загружается на диск если словить это исключение. В общем буду искать причину.

**Comment by Deadooshka** [comment]
Какие-то несовместимости `OpenSSL` с яндексом. Бывает иногда `[curl] 56: SSL read: error:00000000:lib(0):func(0):reason(0), errno 10054` на файлах 200+мб.

**Comment by gelid** [comment]
@Deadooshka , тестируемые файлы не превышают 15 мб (по заданию больше и не надо), а с картинками там вообще 800кб
@loginwashere , да, файлы загружаются, но в ответ приходит ошибка. и тут боюсь будет непонятно загрузился ли файл или пришла реальная ошибка (например кончилось место, диск недоступен или что то еще). В любом случае спасибо. жду результатов если получится разобраться.
