### ISSUE TITLE
Ошибка при обновлении

### ISSUE THREAD

**Issue by avesgit** [nixsolutions/yandex-php-library#120]
Problem 1
    - nixsolutions/yandex-php-library dev-master requires guzzlehttp/guzzle 5.3.0 -> no matching package found.
    - nixsolutions/yandex-php-library dev-master requires guzzlehttp/guzzle 5.3.0 -> no matching package found.
    - Installation request for nixsolutions/yandex-php-library dev-master -> satisfiable by nixsolutions/yandex-php-library[dev-master].

Potential causes:
 - A typo in the package name
 - The package is not available in a stable-enough version according to your minimum-stability setting
   see <https://groups.google.com/d/topic/composer-dev/_g3ASeIFlrc/discussion> for more details.

Read <https://getcomposer.org/doc/articles/troubleshooting.md> for further common problems.

guzzlehttp/guzzle dev-master без него не работает другой пакет

**Comment by loginwashere** [comment]
После тега 0.4.1 в мастере был переход к использованию guzzlehttp/guzzle 5 и php 5.4.
У нас уже висят заведенные таски по переходу к guzzlehttp/guzzle 6 (#89)  и php 5.5 (#91), но я пока затрудняюсь назвать сроки, когда этот переход состоится.
На данный момент можете попробовать использовать 0.4.1 версию библиотеки где еще используется guzzle 3.

**Comment by loginwashere** [comment]
@avesgit перешли на использование guzzle 6 в master
