### ISSUE TITLE
Не работают примеры

### ISSUE THREAD

**Issue by AquaGen** [nixsolutions/yandex-php-library#121]
Я скачал примеры, чтобы посмотреть как они работают. А они не работают. Что делать?
Подобные ошибки везде

Warning: require_once(C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test\settings.php on line 11

Fatal error: require_once(): Failed opening required 'C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test\settings.php on line 11

Открываются страницы, которых не существует
c:\Program%20Files%20%28x86%29\EasyPHP-DevServer-14.1VC11\data\localweb\test\Disk/../OAuth/

Каждую минуту какие-то ошибки
 Fatal error: Call to undefined method Yandex\OAuth\OAuthClient::getClient() in phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/OAuth/yandex-php-library_master.phar/src/Yandex/OAuth/OAuthClient.php on line 254

На страничке  Пример работы с Яндекс Диском нет ничего кроме надписи  Пример работы с Яндекс Диском

/test/examples/Disk/api/disc-space-info.php
<br />
<b>Fatal error</b>:  Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate' in phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
Stack trace:
#0 phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array)
#1 phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #134)
#2 phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.ph in <b>phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php</b> on line <b>51</b><br />

в каждом файле какие-то ошибки. так ничего и не заработало
<br />
<b>Notice</b>:  Undefined index: directory in <b>C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test\examples\Disk\api\directory-contents.php</b> on line <b>17</b><br />
<br />
<b>Fatal error</b>:  Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate' in phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127
Stack trace:
#0 phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php(91): GuzzleHttp\Ring\Client\CurlFactory::createErrorResponse(Array, Array, Array)
#1 phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlHandler.php(96): GuzzleHttp\Ring\Client\CurlFactory::createResponse(Array, Array, Array, Array, Resource id #126)
#2 phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.ph in <b>phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Exception/RequestException.php</b> on line <b>51</b><br />

**Comment by loginwashere** [comment]
> Warning: require_once(C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test/../vendor/autoload.php): failed to open stream: No such file or directory in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test\settings.php on line 11

Судя по этому предупреждению вам нужно добавить файл с настроками (settings.ini) рядом с settings.php. Пример есть в [settings.example.ini](settings.example.ini).
После добавления файла необходимо добавить туда нужные настройки.

> Fatal error: require_once(): Failed opening required 'C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test/../vendor/autoload.php' (include_path='.;C:\php\pear') in C:\Program Files (x86)\EasyPHP-DevServer-14.1VC11\data\localweb\test\settings.php on line 11

Судя по этой ошибке вы не установили зависимости при помощи composer

> Fatal error: Uncaught exception 'GuzzleHttp\Ring\Exception\RingException' with message 'cURL error 60: SSL certificate problem: unable to get local issuer certificate' in phar://C:/Program Files (x86)/EasyPHP-DevServer-14.1VC11/data/localweb/test/examples/Disk/api/yandex-php-library_master.phar/vendor/guzzlehttp/ringphp/src/Client/CurlFactory.php:127

Эта ошибка появляется скорее всего из-за проблем с локалным сертификатом. Я еще пока не знаю как ее воспроизвести, но попробуйте глянуть есть ли у вас локально сертификат как советуют в этом [ответе](http://stackoverflow.com/a/30753741/1384052)

**Comment by loginwashere** [comment]
Скоре всего у вас в php.ini не указан путь к сертификату в curl.cainfo и скорее всего решение можете глянуть [тут](http://stackoverflow.com/a/19149687/1384052)

**Comment by vandroids** [comment]
В примере с Яндекс-диском в самом начале:
$diskClient = new DiskClient(ACCESS_TOKEN);

Скажите пожалуйста, как мне получить OAuth токен для своего приложения (именно для приложения, а не текущего веб-пользователя)? 

Есть ли возможность вместо токена просто указать email/password?

**Comment by Deadooshka** [comment]
Как изменить CURLOPT_SSL_VERIFYPEER через DiskClient, и вообще параметры curl.

**Comment by loginwashere** [comment]
@Deadooshka попробуйте сделать что-то вроде
```
$diskClientHttpClient = $diskClient->getClient();
$diskClientHttpClientConfig = $diskClientHttpClient->getConfig();
$diskClientHttpClientConfig['verify'] = false;
$diskClientHttpClient = new \GuzzleHttp\Client($diskClientHttpClientConfig);
$diskClient->setClient($diskClientHttpClient);
```
