### ISSUE TITLE
oauth tokens 

### ISSUE THREAD

**Issue by G1K** [nixsolutions/yandex-php-library#122]
После этого обновления отвалились нафиг получение токена композер подтянул обновку и я получил лишние 15 минут радости от поломки рабочего решения.
https://github.com/nixsolutions/yandex-php-library/commit/5c95adaf303b46cf8dd9e99ef5db633771a412ae

Судя по коммиту добавилась возможность настраивать прокси.
$client = $this->getClient();

Но из за того что нигде не объявляется получаем исключение

**Comment by loginwashere** [comment]
Спасибо, что сообщили о проблеме.
Постараюсь поскорее исправить.
