### ISSUE TITLE
Получение token

### ISSUE THREAD

**Issue by zhenya91** [nixsolutions/yandex-php-library#135]
Добрый день. 
Пытаюсь получить access token. 
Делаю как написано в примере 
```
$client = new OAuthClient($this->id,$this->password);

        try{
            // осуществляем обмен
            $client->requestAccessToken($_REQUEST['code']);
        }catch (AuthRequestException $e)
        {
            echo $e->getMessage();
        }

        // забираем полученный токен
        $strToken = $client->getAccessToken();
```
Но получаю ошибку 
Yandex\OAuth\Exception\AuthRequestException

Service responsed with error code "Malformed Authorization header".
Caused by: GuzzleHttp\Exception\ClientException
Client error: `POST https://oauth.yandex.ru/token` resulted in a `401 UNAUTHORIZED` response:
{"error": "Malformed Authorization header"}

Подскажите в чем может быть проблема.

**Comment by loginwashere** [comment]
Добрый день.
Действительно проблема имеется - смог воспроизвести.
Постараюсь исправить как можно скорее.
