### ISSUE TITLE
Metrika Stat error

### ISSUE THREAD

**Issue by DjGlobal** [nixsolutions/yandex-php-library#140]
Добрый день! 
Попробовал воспроизвести пример:
`$paramsModel = new Yandex\Metrica\Stat\Models\ByTimeParams();`
`$paramsModel`
`    ->setMetrics(\Yandex\Metrica\Stat\MetricConst::S_HITS)`
`    ->setId($counterId)`
`    ->setDate1('6daysAgo')`
`    ->setDate2('today')`
`    ->setGroup('day');`
`$data = $statClient->data()->getByTime($paramsModel);`

Словил ошибку: 
> Call to undefined function GuzzleHttp\Handler\curl_reset() in phar:///var/www/_/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 78

**Comment by loginwashere** [comment]
Похоже версия PHP, которую вы используете не совместима с последними версиями библиотеки.
Судя по документации для [curl_reset](http://php.net/manual/en/function.curl-reset.php) требуется версия PHP >=5.5.0.
Разъяснения относительно версий библиотеки и используемых версий Guzzle можно посмотреть [здесь](https://github.com/nixsolutions/yandex-php-library#Версии).
То есть как оптимальное решение предлагаю попробовать проверить воспроизводится ли данная проблема на более свежей версии PHP. Если все в порядке возможно стоит рассмотреть возможность перехода на эту более новую версию.
Если использовать другую версию PHP не представляется возможным остается вариант с использованием более старых версий библиотеки.

**Comment by DjGlobal** [comment]
Спасибо! Обновился до 5.5, всё работает.
