### ISSUE TITLE
Добавить поддержку списоков метрик, группировок и сортировок для формирования Отчетов Metrica

### ISSUE THREAD

**Issue by naxel** [nixsolutions/yandex-php-library#145]
Добавить возможность передавать массивы параметров для metrics, dimensions и sort.
Актуально для:
https://tech.yandex.ru/metrika/doc/api2/api_v1/bytime-docpage/
https://tech.yandex.ru/metrika/doc/api2/api_v1/data-docpage/

Основано на комментарии https://github.com/nixsolutions/yandex-php-library/pull/144#issuecomment-196050650

**Comment by xgamtx** [comment]
Уже добавлен функционал в https://github.com/nixsolutions/yandex-php-library/pull/153
