### ISSUE TITLE
Проблемы с загрузкой файла больше 2 мб

### ISSUE THREAD

**Issue by igorhmelevskoy** [nixsolutions/yandex-php-library#157]
UPD: Ошибка появляется при следующей ситуации.
1. Загружаем через api файл - все отлично.
2. Если удалить файл который загрузили (тоесть отправить его в корзину) и повторно попробовать загрузить такой же файл (даже с другим именем) то появляется данная ошибка.
3. Но если очистить корзину и повторить загрузку данного файла - все отлично.
## Я считаю что это БАГ api или же самого диска... Мне кажется что так не должно быть.

UPD: проблема выявлена с типами файлов как .avi .pptx
## .zip больше 5 мб загрузился отлично.

Файл сам загружается но нет потом публикации файла, выдается следующая ошибка.
Fatal error: Uncaught exception 'GuzzleHttp\Exception\RequestException' with message 'cURL error 55: select/poll returned error (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)' in phar:///home/str11/dips222.com/sya/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php:187 Stack trace: #0 phar:///home/str11/dips222.com/sya/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(150): GuzzleHttp\Handler\CurlFactory::createRejection(Object(GuzzleHttp\Handler\EasyHandle), Array) #1 phar:///home/str11/dips222.com/sya/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php(103): GuzzleHttp\Handler\CurlFactory::finishError(Object(GuzzleHttp\Handler\CurlHandler), Object(GuzzleHttp\Handler\EasyHandle), Object(GuzzleHttp\Handler\CurlFactory)) #2 phar:///home/str11/dips222.com/sya/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlHandler.php(43): GuzzleHttp\Handler\CurlFactory::finish(Object(GuzzleH in phar:///home/str11/dips222.com/sya/yandex-php-library_master.phar/vendor/guzzlehttp/guzzle/src/Handler/CurlFactory.php on line 187

вот последовательность кода
$diskClient->uploadFile(
    ''.$dir.'',
    array(
        'path' => $fileName,
        'size' => filesize($fileName),
        'name' => $file
    )
);
$path = $dir.$file;
echo $url = $diskClient->startPublishing($path);

**Comment by holdmann** [comment]
Судя по ошибке:

CURLE_SEND_ERROR (55) Failed sending network data.

Проблема не в библиотеке, а вероятнее всего в канале связи

**Comment by igorhmelevskoy** [comment]
С каналом все норм, уже и хостинг тестил говорил проблема в самой библиотеке.

**Comment by spytz** [comment]
Выполнил описанные шаги с использованием версии 3.0.0:
1) Загрузил с помощью скрипта [/examples/Disk](https://github.com/nixsolutions/yandex-php-library/blob/master/examples/Disk/index.php#L22)  2 файла .avi и .pptx
2) Удалил загруженные файлы через веб-интерфейс https://disk.yandex.ua/client/disk/. Файлы в корзине
3) Повторно загрузил эти же файлы - проблема не обнаружена
4) Удалил файлы через контекстное меню Delete из [/examples/Disk](https://github.com/nixsolutions/yandex-php-library/blob/master/examples/Disk/js/application/views/context_menu.js#L26). Файлы в корзину не попали
5) Еще раз загрузил эти же файлы - проблема не обнаружена

Оба раза файлы успешно загружены на Яндекс Диск
