### ISSUE TITLE
Ошибка в значении константы Metrica/Stat/DomensionsConst

### ISSUE THREAD

**Issue by sandbernar** [nixsolutions/yandex-php-library#158]
yandex-php-library/src/Yandex/Metrica/Stat/DimensionsConst.php[180] const S_TRAFFIC_SOURCE = "ym:s:TrafficSource";

При использовании данной константы выдает ошибку:
"Неверно указан атрибут, значение: ym:s:TrafficSource, код ошибки: 4001"

А с таким значением все ок: "ym:s:trafficSource"

**Comment by Dominus77** [comment]
Установлена версия yandex-php-library v1.0.0
Пример сравнения сегметнов (визиты с мобильных и не мобильных устройств):
```
$paramsModel = new Yandex\Metrica\Stat\Models\ComparisonParams();
$paramsModel
    ->setMetrics(\Yandex\Metrica\Stat\MetricConst::S_USERS)
    ->setId($counterId)
    ->setDimensions(\Yandex\Metrica\Stat\DimensionsConst::S_TRAFFIC_SOURCE)
    ->setFiltersA("ym:s:isMobile=='Yes'")
    ->setFiltersB("ym:s:isMobile=='No'");
$data = $statClient->data()->getComparisonSegments($paramsModel);
```
Ответ: Service responded with error code: "400" and message: "Bad Request"

При разборе выяснилось, что константа \Yandex\Metrica\Stat\DimensionsConst::S_TRAFFIC_SOURCE задана не верно.

А так работает:
```
$paramsModel = new Yandex\Metrica\Stat\Models\ComparisonParams();
$paramsModel
    ->setMetrics(\Yandex\Metrica\Stat\MetricConst::S_USERS)
    ->setId($counterId)
    ->setDimensions("ym:s:trafficSource")
    ->setFiltersA("ym:s:isMobile=='Yes'")
    ->setFiltersB("ym:s:isMobile=='No'");
$data = $statClient->data()->getComparisonSegments($paramsModel);
```

**Comment by spytz** [comment]
Судя по примерам из https://tech.yandex.ru/metrika/doc/api2/api_v1/examples-docpage/#comparison константа действительно должна иметь значение "ym:s:trafficSource"
