### ISSUE TITLE
работа с контентом маркета через партнерский API

### ISSUE THREAD

**Issue by AndreyBobrov** [nixsolutions/yandex-php-library#167]
Маркет предоставляет возможность магазинам, размещающимся на маркете, получать некоторую ограниченную информацию из контента, например информацию о модели товара ( https://tech.yandex.ru/market/partner/doc/dg/reference/content-methods-docpage/ ) или список предложений кампании. Есть ли возможность в этой библиотеке использовать партнерский клиент для этих целей, или реализована только работа с заказами?

**Comment by spytz** [comment]
Эта возможность будет добавлена в https://github.com/nixsolutions/yandex-php-library/pull/179
