### ISSUE TITLE
Дата снимка и другая информация (geotags etc)

### ISSUE THREAD

**Issue by rodendron** [nixsolutions/yandex-php-library#169]
Добрый день,
ЯндексДиск API по идее может отображать дополнительную информацию о фотоснимке. Например, одно из самых важных - дата снимка. Не дата создания файла на диске и не дата его редактирования, а именно дата снимка. Она доступна и при просмотре в браузере файла.
Ровно как и геотэги. Они тоже хранятся в файле, если фотоаппарат поддерживают такую функцию.
Существует ли у библиотеки возможность их считывания?
И если нет, то не могли бы вы подсказать, в какой ветке объекта и в какой функции в файле DiskClient.php можно туда достучаться?
Заранее благодарен за ответ.

**Comment by loginwashere** [comment]
Здравствуйте.
Попробовал поискать ответ в документации.
В том способе работы с диском который поддерживается в этой библиотеке единственное что нашел https://tech.yandex.ru/disk/doc/dg/reference/propfind_property-request-docpage/. Не уверен что туда что-то записывается по умолчанию включая ту информация которая Вас интересует.
Можете скинуть ссылку на документация описывающую получение интересующей Вас информации?

**Comment by rodendron** [comment]
Да, Вы правы.
Я изучил эту документацию от и до и как раз подумал про это место. Но скорее всего, оно только для пользовательской метаинформации.

Нужное видел вот здесь:
https://tech.yandex.ru/fotki/doc/operations-ref/photo-get-docpage/
И далее Atom Entry.

Но к сожалению, это документация уже к другому сервису - Фотки. Но и там есть только дата и время снимка с адресной информацией, а, например, используемый тип фотокамеры отсутствует...
Еще заметил такую особенность - при выборе превью фото формата XL, с сервиса Фотки автоматически фото уменьшается пропорционально, а вот при выборе аналогичной функции с Яндекс.Диск - размер начинает обрезаться криво, особенно это заметно у вертикальных снимков. Это и в Ваших примерах с github я проверял. Но вина не в них.

Меня смутил пункт "Время снимка", добавленный в веб-версии Яндекс.Диска (при нажатии на фаил и просмотре справа его свойств). Видимо, они это вытащили в вебе для JPG файлов, а в API не предусмотрено.

У меня остается один выбор для моих нужд - с помощью Вашей чудесной (без сарказма) библиотеки сохранять фаил в TMP, а далее брать уже полный EXIF (gps, дата снимка). Делать самому маленький Preview и удалять его :) Траффик серверный вот жалко только...

Спасибо за отклик. Закрываем тогда?
Вопрос такой - имеет смысл в Яндекс написать с предложением по включить возможность read_exif в API?

**Comment by AntonShevchuk** [comment]
Давайте таск закрываем, а по запросу в Я - я думаю лучше написать, с учётом что функционал у них в загашниках есть, то и реализовать его в API не составит особого труда.
