### ISSUE TITLE
Composer dev-master

### ISSUE THREAD

**Issue by G1K** [nixsolutions/yandex-php-library#196]
Почему то в https://packagist.org/packages/nixsolutions/yandex-php-library#dev-master

Даже в ветке dev-master крайний коммит 5f1670b0f78f6de0804fd96b8d409c2d2e812c24 

В итоге обновиться нормально не удается, мб хук отвалился.

**Comment by spytz** [comment]
Привет, 
как вы определяете крайний коммит?
По ссылке https://packagist.org/packages/nixsolutions/yandex-php-library#dev-master вижу Source reference 1dc1a51956383a444b352402f6ef0f4fe8886efb ([screenshot](http://storage8.static.itmages.com/i/17/0329/h_1490795947_9836229_3f597dbaff.png))

**Comment by G1K** [comment]
Да именно там был старый коммит, возможно сейчас подтянулось..
