### ISSUE TITLE
Обновить в зависимостях версии 1.0.0 версию guzzle 5.3.0 -> 5.3.1

### ISSUE THREAD

**Issue by gladyshev** [nixsolutions/yandex-php-library#206]
В версии guzzlehttp 5.3.0 есть баг, который [исправили](https://github.com/guzzle/guzzle/pull/1675) в версии 5.3.1.

**Comment by San4o2008** [comment]
добавлено в версии 1.0.1

**Comment by AntonShevchuk** [comment]
https://github.com/nixsolutions/yandex-php-library/releases/tag/1.0.1
