### ISSUE TITLE
Ошибки при загрузке файла на яндекс.диск

### ISSUE THREAD

**Issue by fremail** [nixsolutions/yandex-php-library#244]
С 10 октября выскакивает исключение при загрузке файла на диск.
`cURL error 52: Empty reply from server (see http://curl.haxx.se/libcurl/c/libcurl-errors.html)`

При этом файл загружается успешно.

Создание публичной ссылки для загруженного файла тоже выкидает исключение:
`Service responded with error code: "404" and message: "Not Found"`

**Comment by fremail** [comment]
Оказывается, при длительной загрузке файла (более 20 минут), возвращается пустой ответ, хотя файл успешно сохраняется. Создание публичной ссылки не работает т.к. файл еще не до конца загрузился

**Comment by djdance** [comment]
исходим из того, что введена задержка 1 минута на каждый мегабайт.
