### ISSUE TITLE
Migrate to Guzzle version 5.0

### ISSUE THREAD

**Issue by sergebezborodov** [nixsolutions/yandex-php-library#63]
Приветствую!

В библиотеке используется старая версия guzzle, если я правильно понял - для совместимости с php 5.3?

Вы жестко завязаны на старую версию php или все таки планируется обновление до более новой и использование guzzle 4?

**Comment by im-denisenko** [comment]
Зашел сюда, чтобы найти этот вопрос. 
+1, используемый guzzle устарел на две мажорных версии.

**Comment by PheRum** [comment]
Для тех, кто вынужден по каким-то причинам использовать php53, предлагаю оставить версию 0.3.0 с зависимостью старого Gruzle.
А в самой ветке мастер, продолжить работу над библиотекой и обновить зависимости на актуальные версии
