### ISSUE TITLE
Ошибка при закачке файла на Я.диск

### ISSUE THREAD

**Issue by zaxse** [nixsolutions/yandex-php-library#65]
Установил через  Composer
"nixsolutions/yandex-php-library": "dev-master"

При попытке отправки файла, ошибка:

Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 55: select/poll returned error [url] https://webdav.yandex.ru/ПУТЬ/ИМЯ_ФАЙЛА.pdf' in /var/www/********/_lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338 Stack trace: #0 /var/www/********/_lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #1 /var/www/********/_lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array) #2 /var/www/********/_lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages() #3 /var/www/********/_lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles() #4 /var/www/pira. in /var/www/********/_lib/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php on line 338

**Comment by zaxse** [comment]
Здравствуйте. Версия 0.4.0. Ошибка вновь появилась:

PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 55: SSL_write() returned SYSCALL, errno = 32 [url] https://webdav.yandex.ru/****************.file' in /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338
Stack trace:
#0 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(105): Guzzle\Htt in /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php on line 338

Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 55: SSL_write() returned SYSCALL, errno = 32 [url] https://webdav.yandex.ru/*********************.file' in /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338
Stack trace:
#0 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#1 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(244): Guzzle\Http\Curl\CurlMulti->processResponse(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)
#2 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(227): Guzzle\Http\Curl\CurlMulti->processMessages()
#3 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(211): Guzzle\Http\Curl\CurlMulti->executeHandles()
#4 /var/www/user/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(105): Guzzle\Htt in /var/www/pira/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php on line 338

**Comment by matysik** [comment]
Та же проблема, странным образом срабатывает то на одних, то на других файлах.
