### ISSUE TITLE
Планируется ли реализовать блочную загрузку файлов на яндекс.диск?

### ISSUE THREAD

**Issue by smelukov** [nixsolutions/yandex-php-library#68]
Здравствуйте!
Сейчас, на сколько я вижу из исходников, содержимое файла берется с помощью file_gut_contents.
С большими файлами это не совсем удобно.
Вот хорошо бы отдавать такие файлы маленькими блочками по 5-10 метров :)
Спасибо

**Comment by Deadooshka** [comment]
Да, наверное, лучше curl'у скормить CURLOPT_INFILE как-то (надо guzzle смотреть), а file_get_contents совсем не годится. Если файл больше 300мб, то PHP валится из-за ограничений по памяти в php.ini (вряд ли у кого больше).

**Comment by selifan** [comment]
Возможно, это из-за того, что я пробую находясь за корпоративным прокси, но при отправке (put) файла размером 1.2 МБ валит эксепшн с возвратом http-ошибки 417:
(файл около до 600 К проходит ОК)
**Fatal error: Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 56: Received HTTP code 417 from proxy after CONNECT [url] https://webdav.yandex.ru/evzr/MyBigFile.gz' in phar://D:/webdev/inc/yandex-php-library.phar/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338 Stack trace: #0 phar://D:/webdev/inc/yandex-php-library.phar/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php(279): Guzzle\Http\Curl\CurlMulti->isCurlException(Object(Guzzle\Http\Message\EntityEnclosingRequest), Object(Guzzle\Http\Curl\CurlHandle), Array)**
