### ISSUE TITLE
Yandex Metrica/API отчетов v1

### ISSUE THREAD

**Issue by 3Jloy** [nixsolutions/yandex-php-library#69]
При получении данных всегда возвращается exception c сообщением Forbidden, пробовал пример из Wiki и также примеры поставляемые с библиотекай  (директория examples), токен получал как вручную(отладочный токен) так и при помощи oAuth результат одинаков.

**Comment by b0zar** [comment]
Сам наткнулся на нерабочий пример:
```php
use Yandex\Metrica\Stat\StatClient;
$statClient = new StatClient(ACCESS_TOKEN);

$paramsModel = new \Yandex\Metrica\Stat\Models\TableParams();
$paramsModel
    ->setPreset(\Yandex\Metrica\Stat\AvailableValues::PRESET_TECH_PLATFORMS)
    ->setDimensions(\Yandex\Metrica\Stat\DimensionsConst::S_BROWSER)
    ->setId($counter->getId());
$data = $statClient->data()->getTable($paramsModel);
```
Проблема находится в кусочке:
```php
$statClient->data()
```
```php
/**
 * @return DataClient
 */
public function data()
{
    return new DataClient();
}
```
```php
/**
 * @param string $token access token
 */
public function __construct($token = '')
{
    $this->setServiceScheme(self::HTTPS_SCHEME);
    $this->setAccessToken($token);
}
```

Для доступа к данным нужен токет, но он нигде не указан. Для коректной работы его нужно установить вручную. Рабочий пример:
```php
use Yandex\Metrica\Stat\StatClient;
$statClient = new StatClient(ACCESS_TOKEN);

$paramsModel = new \Yandex\Metrica\Stat\Models\TableParams();
$paramsModel
    ->setPreset(\Yandex\Metrica\Stat\AvailableValues::PRESET_TECH_PLATFORMS)
    ->setDimensions(\Yandex\Metrica\Stat\DimensionsConst::S_BROWSER)
    ->setId($counter->getId());
$data = $statClient->data();
$data->setAccessToken(ACCESS_TOKEN);
$data = $data->getTable($paramsModel);
```
Почему не передавать токен из ```StatClient```  в  ```DataClient```, я не знаю.

P.S. Никакой информации в google не нашел, кроме этого запроса. Решил отписать, возможно кому-то будет полезно.

**Comment by AntonShevchuk** [comment]
Привет
Спасибо за информацию, постараемся по возможности проверить и исправить

**Comment by imsha** [comment]
Спасибо, помогло

**Comment by holdmann** [comment]
According to @ivansky pull request (https://github.com/nixsolutions/yandex-php-library/pull/79) the best solution is force set access token to DataClient constructor.

```
    /**
     * @return DataClient
     */
    public function data()
    {
        $accessToken = $this->getAccessToken();
        return new DataClient($accessToken);
    }
```
