### ISSUE TITLE
Не могу вывести содержимое каталога.

### ISSUE THREAD

**Issue by stalker-people** [nixsolutions/yandex-php-library#73]
Доброго времени суток!
У меня происходит инициализация, но я не могу вывести список какталога.
Скажите пожалуйсата, где здесь ошибка?

Исходник:
<?
require_once 'phar://yandex-php-library_master.phar/vendor/autoload.php';
include "config.php";
?>

<html>
<head>
<meta charset='utf-8'>
<title>Ретранслятор файлов Яндекс.Диска</title>
</head>
<body>
<?

use Yandex\Disk\DiskClient;
$diskClient = new DiskClient(ACCESS_TOKEN);
$diskClient->setServiceScheme(DiskClient::HTTPS_SCHEME);
$dirContent = $diskClient->directoryContents('/');

foreach ($dirContent as $dirItem) {
    if ($dirItem['resourceType'] === 'dir') {
        echo 'Директория "' . $dirItem['displayName'] . '" была создана ' . date(
                'Y-m-d в H:i:s',
                strtotime($dirItem['creationDate'])
            ) . '<br />';
    } else {
        echo 'Файл "' . $dirItem['displayName'] . '" с размером в ' . $dirItem['contentLength'] . ' байт был создан ' . date(
                'Y-m-d в H:i:s',
                strtotime($dirItem['creationDate'])
            ) . '<br />';
    }
}
?>

</body>
</html>

Результат в браузере:

Fatal error: Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'The PHP cURL extension must be installed to use Guzzle.' in phar:///home/alex/web_chaes2/files/yadisk_file_retranslate/yandex-php-library_master.phar/vendor/guzzle/http/Guzzle/Http/Client.php:70 Stack trace: #0 phar:///home/alex/web_chaes2/files/yadisk_file_retranslate/yandex-php-library_master.phar/src/Yandex/Disk/DiskClient.php(134): Guzzle\Http\Client->__construct('https://webdav....') #1 /home/alex/web_chaes2/files/yadisk_file_retranslate/index.php(18): Yandex\Disk\DiskClient->directoryContents('/') #2 {main} thrown in phar:///home/alex/web_chaes2/files/yadisk_file_retranslate/yandex-php-library_master.phar/vendor/guzzle/http/Guzzle/Http/Client.php on line 70

**Comment by Jekis** [comment]
Вам нужно установить curl extension для php.

Для убунту это http://askubuntu.com/a/9296/203581
Для других ОС воспользуйтесь поиском

**Comment by stalker-people** [comment]
Jekis, благодарю вас.

**Comment by AntonShevchuk** [comment]
Оперативно :+1: 
Закрываю
