### ISSUE TITLE
ошибки при использовании php библиотеки Яндекс.Диска

### ISSUE THREAD

**Issue by tekunova** [nixsolutions/yandex-php-library#77]
При использовании библиотеки для php яндекс диска (https://github.com/nixsolutions/yandex-php-library/wiki/Yandex-Disk)
периодически появляются ошибки curl 55 и 56
например, при попытке загрузки файла появилась ошибка:
[curl] 55: select_/poll returned error_ [url] https://webdav.yandex.ru/Исходящие-0115/21-43___008.PDF
!!! при этом файлы то загружаются без проблем, то появляются эти ошибки
можете ли вы что-то порекомендовать?

**Comment by AntonShevchuk** [comment]
Проверить после переезда на новый Guzzle #63 
Возможно проблема кроется в #68

**Comment by Deadooshka** [comment]
ошибки с *_master.phar (php5.6.10)
~~~~~~
[14-Jun-2015 11:56:54 Europe/Moscow] PHP Fatal error:  Uncaught exception 'Guzzle\Http\Exception\CurlException' with message '[curl] 35: Unknown SSL protocol error in connection to webdav.yandex.ru:443  [url] https://webdav.yandex.ru/' in phar://<...>/yandex-php-library_master.phar/vendor/guzzle/http/Guzzle/Http/Curl/CurlMulti.php:338 <...>
~~~~~~
в *_0.4.0.phar без ошибок

**Comment by naxel** [comment]
yandex-php-library_0.4.0.phar - на данный момент являеться самой свежей версией phar-архива. yandex-php-library_master.phar - был сбилджен до 0.4.0 и вероятно в него не входят последнии фиксы, поэтому лучше используйте тегированные версии библиотеки.
