### ISSUE TITLE
Переименуем Metrica в Metrika?

### ISSUE THREAD

**Issue by holdmann** [nixsolutions/yandex-php-library#84]
Кто за то, чтобы не задумываться каждый раз когда печатаешь "Metrika"? Могу пул реквест сообразить :) Ставьте +1 в комментах, наберется 10, сделаю!

**Comment by SergeR** [comment]
:+1:  :smile:

**Comment by ivansky** [comment]
:+1: :muscle:

**Comment by tanchik194** [comment]
Дело в том, что на англоязычных ресурсах используется Metrica (https://metrica.yandex.com/), хотя на русскоязычных Metrika :smile: 
Думаю стоит придерживаться англоязычной версии.

**Comment by asys-log** [comment]
а что будет если для русских сайтов использовать metriKa все нормально будет????

**Comment by coll3ctor** [comment]
+1

**Comment by AntonShevchuk** [comment]
Ребята, при разработке мы ориентируемся на ресурс https://tech.yandex.com/
Собственно там используется Metrica и Dictionary, а не Metrika и Slovari
