### ISSUE TITLE
guzzle in composer

### ISSUE THREAD

**Issue by atukai** [nixsolutions/yandex-php-library#85]
Composer  говорит, что:

Package guzzle/inflection is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/common is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/stream is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/parser is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/http is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/cache is abandoned, you should avoid using it. Use guzzle/guzzle instead.
Package guzzle/service is abandoned, you should avoid using it. Use guzzle/guzzle instead.

**Comment by AntonShevchuk** [comment]
В следующем релизе мы отказываем от поддержки PHP 5.3 и переезжаем на httpguzzle 5.0, соответственно данные сообщения тоже исчезнут см. #63
