### ISSUE TITLE
Yandex php library: uploadFile() BUG ?

### ISSUE THREAD

**Issue by selifan** [nixsolutions/yandex-php-library#86]
Модуль Disk API - yandex-php-library_master.phar
При попытке выполнить uploadFile вылетает ошибка:

Fatal error: Call to undefined function Yandex\Disk\finfo_open() in phar://D:/webdev/docs/tests/yandex-php-library.phar/src/Yandex/Disk/DiskClient.php on line 333

**Comment by naxel** [comment]
Вероятно у вас не включен fileinfo. Скорее всего вам понадобиться просто расскоментировать строчку php_fileinfo.dll в php.ini и перезапустить веб-сервер

**Comment by selifan** [comment]
Точно, теперь заработало. Подумал из-за namespace-ов что есть там какая-то своя ф-ция fileinfo.
Только еще выяснилось, что если в "папке" назначения нет стартового слеша ("folder/" вместо "/folder/"), модуль вылетает с exception-ом. Конечно, не баг, но...
Спасибо !

**Comment by selifan** [comment]
И еще одна странность - зачем функция directoryContents('/myfolder/') первым элементом возвращает саму папку myfolder, хотя никакой ПОДпапки с таким же именем там нет, и как мне понять, если она там есть - это действительно подпапка, или фича yandex disk API ?
