### ISSUE TITLE
Планируется ли добавление XML и директа?

### ISSUE THREAD

**Issue by alekciy** [nixsolutions/yandex-php-library#92]
Собственно есть личные наработки для работы по API Yаndex.Direct и Yandex.XML. Думаю присоединиться к данному проекту и добавить их суда. Но возможно такая работа уже ведется и эти расширения уже есть?

На хабре читал, что начиналось все с Yandex.XML ( http://habrahabr.ru/company/yandex/blog/231495/ ), но я почему-то данное API тут не вижу.

**Comment by AntonShevchuk** [comment]
По поиску Яндекс.XML - насколько мне известно - нет, дальнейшая разработка и интеграция в бибилотеку не планируется.
По Директ - на данный момент разработка не ведётся, будем рады если поможете :)

**Comment by alekciy** [comment]
А Yandex.XML не планируется, ввиду наличия готовой отдельной библиотеки? Но мне https://code.google.com/p/yandex/ показался не очень живым... Да и все подобные сервисы хочется иметь под капотом одной библиотеки (как это есть у Google, использую в рамках Yii - удобно).

Касательно Yаndex.Direct  понял. Буду готовить запрос на слияние. Ориентировочно середина июля-начало августа.

**Comment by AntonShevchuk** [comment]
Насколько я понял, Я не планируют развивать Yandex.XML в текущем виде, возможно его планируют переделать во что-то иное, поэтому решили оставить разработку как есть.
Библиотеку я действительно не поддерживаю, но если вдруг кто-то захочет её переделать под этот проект, то я прийму пул-реквест ;)

**Comment by alekciy** [comment]
Ок, тогда я и Yandex.XML добавлю, тем паче у меня с него тоже все началось и в целом реализацию я нахожу удачной.

**Comment by AntonShevchuk** [comment]
Проект Yandex.XML теперь живёт тут https://github.com/AntonShevchuk/yandex
Данный вопрос закрываю.
