### ISSUE TITLE
Ошибка Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'Unable to parse response body into XML: xmlns:d: 'DAV:' is not a valid URI '

### ISSUE THREAD

**Issue by paulvales** [nixsolutions/yandex-php-library#98]
Здравствуйте, ошибка :Fatal error: Uncaught exception 'Guzzle\Common\Exception\RuntimeException' with message 'Unable to parse response body into XML: xmlns:d: 'DAV:' is not a valid URI ' in phar:///var/www/v-2348/data/www/stylus.kz/ya/yandex-php-library_master.phar/vendor/guzzle/http/Guzzle/Http/Message/Response.php:899 Stack trace: #0 phar:///var/www/v-2348/data/www/stylus.kz/ya/yandex-php-library_master.phar/src/Yandex/Disk/DiskClient.php(143): Guzzle\Http\Message\Response->xml() #1 /var/www/v-2348/data/www/stylus.kz/ya/index.php(17): Yandex\Disk\DiskClient->directoryContents() #2 {main} thrown in phar:///var/www/v-2348/data/www/stylus.kz/ya/yandex-php-library_master.phar/vendor/guzzle/http/Guzzle/Http/Message/Response.php on line 899

Подключил последнюю версию phar 
Подключал для операций с файлами на яндекс диске. Что можно предпринять?

**Comment by loginwashere** [comment]
Здравствуйте.
Можете проверить воспроизводится ли еще проблема на версиях библиотеки мастер (там был переход на php 5.4 и guzzle 5.3) и 0.4.1.
Если воспроизводится - опишите пожалуйста ваше окружение. Какая операционная система, какая версия php, какие расширения php используются?
