### ISSUE TITLE
Ошибка загрузки больших файлов

### ISSUE THREAD

**Issue by Seriyyy95** [nixsolutions/yandex-php-library#99]
Если попытаться отправить на диск файл размером больше чем количество доступной в php оперативной памяти скрипт валится с ошибкой: Fatal error: Allowed memory size of 134217728 bytes exhausted (tried to allocate 284201810 bytes) in phar:///home/u5503sard/scripts/yandex-sdk_0.2.0.phar/src/Yandex/Disk/DiskClient.php on line 362

**Comment by loginwashere** [comment]
Эта проблема решена на данный момент в мастере как часть перехода на Guzzle 5.3 и php 5.4
